resources:
- deploy.yaml

images:
- name: jamong1014.azurecr.io/backendweb
  newName: jamong1014.azurecr.io/backendweb
  newTag: 0e7ca40822d51f4630dedf5fdc0ccfdb62a0353e
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
